name: FRAMES_CI
on:
  pull_request: 
    branches: ["*"]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x']
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
      
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Installing dependencies
        run: npm install
      - name: Testing it
        run: npm run test
        
        
